permalink: /:year-:month-:day-:title/
paginate: 10
markdown: kramdown
encoding: utf-8

# 作者信息
author: 
  name: 刘德元
  email: liudeyuanfe@gmail.com
  link: morningBeauty.github.io
  github: http://github.com/xiaomibaobao

# 站点信息
title: 小米的博客
description: My personal note-blog.
url: morningBeauty.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
avatar: http://i1.piimg.com/567571/aef5f4c1bec1b634.jpg
favicon: http://i1.piimg.com/567571/aef5f4c1bec1b634.jpg

# google analytics 设置
ga:
  id: UA-74789926-1
  url: http://blog.jimmylv.info

# disqus 设置
disqus:
  shortname: gotoshare

# 主题设置，自动激活某个标签
active: 思考

# 首页除了最新文章外显示分类
cates: 
  - React
  - 摄影

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts

exclude:
  - .idea/